// Action type constants
export const COMBAT_ACTIONS = {
  ATTACK: 'ATTACK',
  DEFEND: 'DEFEND',
  COUNTER: 'COUNTER',
  DODGE: 'DODGE',
  SPECIAL: 'SPECIAL'
};

// Battle event type constants
export const BATTLE_EVENTS = {
  ACTION_PERFORMED: 'ACTION_PERFORMED',
  STATE_UPDATED: 'STATE_UPDATED',
  COMMENTARY_ADDED: 'COMMENTARY_ADDED',
  BATTLE_ENDED: 'BATTLE_ENDED'
};

export const EFFECTS = ['NONE', 'STUN', 'BURN', 'FREEZE', 'BLEED', 'WEAKNESS', 'CONFUSION', 'LOVE', 'TRAPPED', 'POISON', 'SLEEP', 'SLOW', 'LAUGH', 'SADNESS']